import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white h-[100vh] text-black" >
          <div className="bg-black text-white text-center py-2">50% OFF SUMMER SALE & FREE SHIPPING</div>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
